In [1]:
import numpy as np
a=[1,2,3,4]
b=[5,6,7,8]
[a[i]+b[i] for i in range(len(a))]


[6, 8, 10, 12]

In [2]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a[:,1:2]

array([[2],
       [5],
       [8]])

In [6]:
b=np.eye(3,3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.eye(3,3)
c=a*b
c

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

In [8]:
a[1:,::2]

array([[4, 6],
       [7, 9]])

In [9]:
a[1::2,1:]

array([[5, 6]])

In [10]:
a=np.arange(0,10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0,10,5).astype(int)

array([ 0,  2,  5,  7, 10])

In [13]:
a=np.array([1,2,3])
a+a

array([2, 4, 6])

In [14]:
a**2

array([1, 4, 9])

In [15]:
a**a

array([ 1,  4, 27])

In [16]:
a-a

array([0, 0, 0])

In [17]:
a/2

array([0.5, 1. , 1.5])

In [18]:
a=np.arange(0,10).reshape(2,5)
a


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
a.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [20]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [22]:
np.linalg.det(a)

-9.51619735392994e-16

In [23]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a

array([[1, 2],
       [3, 4]])

In [26]:
a=np.arange(0,12).resize(3,4)
a
a=np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
np.resize(a,(4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  1,  2],
       [ 3,  4,  5,  6]])

In [28]:
np.split(a,2)


[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [29]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
c=a.copy()
a,c

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [32]:
c[0]=111

In [33]:
a,c

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([111,   2,   3,   4,   5,   6,   7,   8,   9,  10]))

In [34]:
d=a.view()

In [35]:
a,d

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [36]:
d[0]=1111
a,d

(array([1111,    2,    3,    4,    5,    6,    7,    8,    9,   10]),
 array([1111,    2,    3,    4,    5,    6,    7,    8,    9,   10]))

In [37]:
np.sum(a,axis=0)

1165

In [38]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
a


array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
np.mean(a)

4.5

In [40]:
np.median(a)

4.5

In [41]:
np.std(a)

2.29128784747792

In [42]:
def mean(array):
    n=len(array)
    return np.sum(array)/n
mean(np.array([1,2,3,4,5,6,7]))    

4.0

In [45]:
def variance(array):
       n=len(array)
       m=mean(array)
       return np.sum((array-m)**2)/n


2.9166666666666665

In [46]:
import numpy as np
data=np.array([10,20,30,40,50])
min_val=np.min(data)
max_val=np.max(data)
scaled_data=(np.sum(data)-min_val/max_val-min_val)
print("original data:",data)
print("scaled data:",scaled_data)
variance(np.array([1,2,3,4,5,6]))    

original data: [10 20 30 40 50]
scaled data: 139.8


2.9166666666666665

In [47]:
import numpy as np
data=np.array([10,20,30,40,50])
m=mean(np.array(data))
v=variance(np.array(data))
s=np.sqrt(v)
standard_scalar=(data-m)/s
print("mean:",m)
print("Variance:",v)
print("deviation:",s)
print("Standard scalar:",standard_scalar)

mean: 30.0
Variance: 200.0
deviation: 14.142135623730951
Standard scalar: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [48]:
x=np.array([-3,-1,0,1,3])
sigmoid=1/(1+np.exp(-x))
sigmoid

array([0.04742587, 0.26894142, 0.5       , 0.73105858, 0.95257413])